### ISSUE TITLE
Add component and feature facets to search page

### ISSUE THREAD

**Issue by geoffroy-noel-ddh** [kingsdigitallab/crossreads#45]

**Comment by geoffroy-noel-ddh** [comment]
@simonastoyanova I've added the Components, features and C-F facets to the search page.

**Comment by simonastoyanova** [comment]
Thank you, @geoffroy-noel-ddh. I've noticed a couple of things in these facets, let me know if it makes sense to reopen the ticket or report them separately.

In the list if character for script Latin 1, at the bottom of the list there are a few Greek letters listed, I think a leftover from the testing phase:

![Screenshot 2024-04-10 at 11 50 16](https://github.com/kingsdigitallab/crossreads/assets/4941543/9ad007e0-b21b-4215-86de-a176f6e49ecb)

I don't see them in the list of characters for Latin 1 in the definitions tab. Could you let me know where to look to remove them or should I leave that to you?

Another thing but it's not a bug. I'm thinking about the comp-feat list and whether we should order it by component, e.g. all combinations of festures for a crossbar, rather than by frequency of attestation. Not sure how good of an idea this is, need to think and discuss, but do let me know if you have any thoughts on this.
