### ISSUE TITLE
list of unused components & features

### ISSUE THREAD

**Issue by simonastoyanova** [kingsdigitallab/crossreads#47]
As I annotate, I find that I don't use a number of features which I initially thought would be useful. Would it be possible to extract a list of unused features which I can then delete from the definitions table without the risk of invalidating annotations? 
Similar for unused components, which I haven't noticed but it would be the same issue as with the features.

**Comment by geoffroy-noel-ddh** [comment]
Hi @simonastoyanova The unused components and features are now appearing with a striped background in the definition table.

Could you double check that this looks correct? 

**One thing to keep in mind** is that this status is updated three times a day (after the regular indexing of the annotations for the search page). It won't reflect the changes made to annotations since the last indexing.

![image](https://github.com/kingsdigitallab/crossreads/assets/3778106/4028da1b-cc06-4507-baef-e90a26e9cf37)

**Comment by simonastoyanova** [comment]
@geoffroy-noel-ddh Thank you, looks good and no issues so far. I will report if anything comes up.
