### ISSUE TITLE
Annotations lost when switching from definitions tab to Annotator tab 

### ISSUE THREAD

**Issue by simonastoyanova** [kingsdigitallab/crossreads#63]
@geoffroy-noel-ddh  I was working on https://kingsdigitallab.github.io/crossreads/annotator.html?obj=http://sicily.classics.ox.ac.uk/inscription/ISic000093&img=ISic000093.jpg when I decided to add something to the Definitions. After saving the change I went back to the Annotator tab and all my annotations were gone. I did a hard refresh but nothing changes. I checked the annotations list in the repo and there is nothing for ISic000093. It's as if I haven't worked on that inscription at all. Could you please investigate and let me know?

**Comment by simonastoyanova** [comment]
Oh, and Hide boxes was on, though I doubt that has anything to do with the saving problem.

**Comment by geoffroy-noel-ddh** [comment]
Thanks for letting me know. I'll try to have a look later today or on Monday.

**Comment by geoffroy-noel-ddh** [comment]
@simonastoyanova That's my fault. When I develop locally I often turn a debugging mode on so I can test the annotator without actually saving anything to github. Last time I released my changes to the live site I forgot to disabled that flag.

If that ever happens again by accident, a clear warning message should now appear at the top of the annotator after any attempt to save, to indicate that it didn't occur due to the DEBUG flag.

Sorry about that and thanks for telling me immediatelly.

**Comment by simonastoyanova** [comment]
Got it, thank you for sorting that.
